### ISSUE TITLE
Target JVM

### ISSUE THREAD

**Issue by RohitKushvaha01** [itsaky/yuvakriti#2]
As YuvaKriti is still in its early stages of development,
and given its inspiration from Java and the JVM, 
I would like to suggest that you consider targeting the Java Virtual Machine (JVM) instead of developing our own virtual machine. 

The JVM offers a robust, mature, and widely adopted platform that could provide several benefits:

**Reduced Development Overhead**: By leveraging the JVM, we can focus on developing the language features and syntax without the need to create and optimize our own virtual machine. This would allow to accelerate the development timeline and avoid the complexities associated with VM development.Proven Stability and

** Performance**: 
The JVM has been optimized over decades, offering stability, security, and performance improvements that would be challenging to replicate in a custom VM. This would allow YuvaKriti to benefit from these optimizations without requiring extensive work on our part.

**Wider Adoption and Integration**: Targeting the JVM would make YuvaKriti more accessible to developers familiar with Java and other JVM languages. It would also allow seamless integration with existing Java libraries, tools, and ecosystems, potentially increasing the language's adoption.Focus on Language Innovation: With the JVM handling the lower-level execution details, we can focus more on innovating within the language itself, exploring unique features, and providing a compelling developer experience.

**Comment by itsaky** [comment]
As mentioned in the readme:

> This project was developed during my exploration of Rust, compilers, and virtual machines. Please note that the code may not adhere to best practices. YuvaKriti is intended solely for educational purposes and is not recommended for production use.

This project is not intended for production use.
